from typing import Dict, Any

sampleFamilyTree: Dict[str, Any] = {
    "members": [
        {
            "id": "grand-pere-1",
            "firstName": "Pierre",
            "lastName": "Durand",
            "birthDate": "1945-03-15",
            "gender": "male",
            "photo": "grandfather-avatar",
            "spouseId": "grand-mere-1",
            "childrenIds": ["pere-1", "oncle-1"],
            "generation": 1,
        },
        {
            "id": "grand-mere-1",
            "firstName": "Marie",
            "lastName": "Durand",
            "birthDate": "1948-07-22",
            "gender": "female",
            "photo": "grandmother-avatar",
            "spouseId": "grand-pere-1",
            "childrenIds": ["pere-1", "oncle-1"],
            "generation": 1,
        },
        {
            "id": "oncle-1",
            "firstName": "Paul",
            "lastName": "Durand",
            "birthDate": "1968-04-25",
            "gender": "male",
            "photo": "adulte_1",
            "spouseId": "belle-fille-1",
            "parentIds": ["grand-pere-1", "grand-mere-1"],
            "childrenIds": ["enfant-4"],
            "generation": 2,
        },
        {
            "id": "belle-fille-1",
            "firstName": "Emily",
            "lastName": "Durand",
            "birthDate": "2003-01-24",
            "gender": "female",
            "photo": "belle_fille_1",
            "spouseId": "oncle-1",
            "childrenIds": ["enfant-4"],
            "generation": 2,
        },
        {
            "id": "enfant-4",
            "firstName": "Emma",
            "lastName": "Durand",
            "birthDate": "2003-01-24",
            "gender": "female",
            "photo": "enfant_3",
            "parentIds": ["oncle-1", "belle-fille-1"],
            "generation": 3,
        },
        {
            "id": "pere-1",
            "firstName": "Michel",
            "lastName": "Durand",
            "birthDate": "1970-09-12",
            "gender": "male",
            "photo": "father-avatar",
            "parentIds": ["grand-pere-1", "grand-mere-1"],
            "spouseId": "mere-1",
            "childrenIds": ["enfant-1", "enfant-2"],
            "generation": 2,
        },
        {
            "id": "mere-1",
            "firstName": "Sophie",
            "lastName": "Durand",
            "birthDate": "1972-12-03",
            "gender": "female",
            "photo": "mother-avatar",
            "parentIds": ["grand-pere-2", "grand-mere-2"],
            "spouseId": "pere-1",
            "childrenIds": ["enfant-1", "enfant-2"],
            "generation": 2,
        },
        {
            "id": "enfant-1",
            "firstName": "Lucas",
            "lastName": "Durand",
            "birthDate": "2000-06-18",
            "gender": "male",
            "photo": "enfant_1",
            "parentIds": ["pere-1", "mere-1"],
            "generation": 3,
        },
        {
            "id": "enfant-2",
            "firstName": "Stive",
            "lastName": "Durand",
            "birthDate": "2003-01-24",
            "gender": "male",
            "photo": "enfant_2",
            "parentIds": ["pere-1", "mere-1"],
            "generation": 3,
        },
    ],
    "relationships": {
        "marriages": [
                {
                    "id": "marriage-1",
                    "spouseIds": ["grand-pere-1", "grand-mere-1"],
                    "marriageDate": "1968-06-15",
                    "childrenIds": ["pere-1", "oncle-1"],
                },
                {
                    "id": "marriage-2",
                    "spouseIds": ["pere-1", "mere-1"],
                    "marriageDate": "1998-05-12",
                },
                {
                    "id": "marriage-3",
                    "spouseIds": ["oncle-1", "belle-fille-1"],
                    "marriageDate": "1998-05-12",
                },
        ],
        "parentChild": [
            {"id": "pc-1", "parentId": "grand-pere-1", "childId": "pere-1"},
            {"id": "pc-2", "parentId": "grand-mere-1", "childId": "pere-1"},
            {"id": "pc-3", "parentId": "grand-pere-1", "childId": "oncle-1"},
            {"id": "pc-4", "parentId": "grand-mere-1", "childId": "oncle-1"},
            {"id": "pc-5", "parentId": "pere-1", "childId": "enfant-1"},
            {"id": "pc-6", "parentId": "mere-1", "childId": "enfant-1"},
            {"id": "pc-7", "parentId": "pere-1", "childId": "enfant-2"},
            {"id": "pc-8", "parentId": "mere-1", "childId": "enfant-2"},
            {"id": "pc-9", "parentId": "oncle-1", "childId": "enfant-4"},
            {"id": "pc-10", "parentId": "belle-fille-1", "childId": "enfant-4"},
        ],
    },
}
